Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/LineLength:
  Max: 90

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
